# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{deploy_and_deliver}
  s.version = "1.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Morrison"]
  s.date = %q{2011-04-22}
  s.description = %q{Mark Pivotal Tracker stories as Delivered on deploy.}
  s.email = %q{daniel@collectiveidea.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "README",
     "Rakefile",
     "VERSION",
     "deploy_and_deliver.gemspec",
     "install.rb",
     "lib/deploy_and_deliver/recipes.rb",
     "recipes/deploy_and_deliver.rb"
  ]
  s.homepage = %q{http://github.com/collectiveidea/deploy_and_deliver}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Capistrano recipes for Pivotal Tracker}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

